#spring:
#  application:
#   name: spring boot yml example
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springjwt?useSSL=false
#    username: root
#    password: 11111111

server:
  port: 9192