security:
  oauth2:
    client:
      clientId: ${GIT_HUB_CLIENT_ID}
      clientSecret: ${GIT_HUB_CLIENT_SECRET}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false
    sso:
      login-path: /login
