security:
  oauth2:
    client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET:defaultValue}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: header
      scope: openid,email,profile
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true